---
- name: My Testing Playbook
  hosts: all
  become: true
  tasks:
  - name: install pakage
    yum: 
     name: httpd
     state: latest
    notify: start service

  handlers: 
  - name: start service
    service:
     name: httpd
     state: started
